### ISSUE TITLE
Using <username> and <lab id> does not render properly in docs/technical/storage.md

### ISSUE THREAD

**Issue by rionda** [UMass-RC/unity-docs#2]
https://github.com/UMass-RC/unity-docs/blob/ce5655e75430fa6a929b1fb96c573626a614c12b/docs/technical/storage.md?plain=1#L8

Using `<username>` and `<lab id>` does not render properly, because the `<` and `>` are interpreted as HTML tags (https://unity.rc.umass.edu/docs/technical/storage.html). Consider replacing them with `$username` and `$lab_id` or use backticks, like I did above: `<username>` and `<lab id>`.

There may be similar issues in this and other files, I did not check.

**Comment by rionda** [comment]
Indeed in the same file, for the description of `/scratch`, one finds ` /scratch/<nodeid>/<jobid>`, which does not render correctly.

**Comment by hakasapl** [comment]
Thanks for the bug report. This has been addressed with 7da29b123432ce3275c27cc64e518c8d38351ea9 and will be pushed later today.
